services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FT_MOULINETTE_ADDR=:9090

  sandbox-image:
    build:
      context: .
      dockerfile: Dockerfile.sandbox
    image: ft-moulinette-sandbox:latest
    profiles: ["build-only"]
