FROM gcc:13-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip && \
    pip3 install --no-cache-dir --break-system-packages norminette && \
    rm -rf /var/lib/apt/lists/*

RUN useradd --no-create-home --uid 1000 runner
USER runner

WORKDIR /work