volumes:
  ftp_data:

networks:
  filenet:
    driver: bridge


services:
  apache-server:
    build: ./Apache
    container_name: apache-server
    ports:
      - "8080:80"
    depends_on:
      - ftp-server
    networks:
      - filenet

  ftp-server:
    build: ./Moulinette
    container_name: ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - filenet
    volumes:
      - ftp_data:/home/ftpuser/ftp
